#! /bin/sh

case "$1" in
    start)
        echo "Starting SCULL"
        scull_load
        echo "Starting faulty module"
        module_load faulty
        echo "Starting aesdchar module"
        module_load aesdchar 
        echo "Starting hello module"
        modprobe hello
        echo "done."
        ;;
    stop)
        echo "Stopping hello module"
        rmmod hello
        echo "Stopping aesdchar module"
        module_unload aesdchar
        echo "Stopping faulty module"
        module_unload faulty
        echo "Stopping SCULL"
        scull_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"     
        exit 1
esac
exit $?
